export const AreaOfGovAndAdminList = 
    [
        'Airlines and Baggage',
        'Customs', 
        'Immigration', 
        'Airport Facilities', 
        'Other',
        'Exchanges and Deposits of Cash', 
        'Rules and Regulations', 
        'Loans', 
        'Other',
        'Visa', 
        'Illigal Resident', 
        'Other',
        'VAT', 
        'Service Tax', 
        'Professional Tax', 
        'Commercial Tax', 
        'Sales Tax', 
        'Other',
        'Service Tax', 
        'Excise', 
        'Custom Check and Clearance', 
        'Others',
        'School or College Related', 
        'Scholarships', 
        'Pension Processing', 
        'Marks Cards and Transcripts', 
        'Employee Grievances', 
        'Certificates', 
        'Others',
        'Transformers', 
        'Services', 
        'Policies and Procedures', 
        'Payment and Arrears', 
        'Employee Grievances', 
        'Electricity Connection', 
        'Electric Meters', 
        'Domestic', 
        'Commercial and Industrial', 
        'Others',
        'Policies and Procedures', 
        'Pharmacy', 
        'Food License', 
        'Drug License', 
        'Others',
    'Ration Card', 'LPG Gas Cylinder', 'Food and Supply', 'Fire License', 'Others','Policies and Procedures', 'Embezzlement', 'Trading in influence', 'Patronage', 'Nepotism', 'Cronyism', 'Gombeenism', 'Parochialism', 'Corrupt Bidding (Kickbacks)', 'Unholy Alliance', 'Involvement in Organized Crime', 'Others'
    ,'Saplings and Tree Cover', 'Timber Related', 'Protected Forest and Sanctuaries', 'Others',
    'Pest Control', 'Hospitals and Medical Care', 'Health Services', 'Health and Family', 'Government Schemes', 'Employee State Insurance', 'Employee Grievance', 'Disability Related', 'Others'
    ,'TAN', 'Policies and Procedures', 'PAN', 'Income Tax', 'Others',
    ,'Insurance Application and Claims', 'Report about a Third Party vendors Contracted by Companies', 'Report about a Bribery incident in a Insurance Company', 'Report about a Malpractice in a Insurance Company', 'Report about a Fraudulent Insurance Company', 'Report about a Fraudulent Insurance Employee', 'Report about a poor due diligence in writing policies by Insurance Companies', 'Report about a Novel Fraud Incident', 'Report about a Lower Premium Incident', 'Others',
    ,'Services', 'Policies and Procedures', 'PIL', 'Notary', 'Court Related', 'Others',
    ,'Employee State Insurance', 'Registrations and Licenses', 'Provident Fund', 'Policies and Procedures', 'Pension', 'Employee Grievances', 'Report a Malpractice Incident in Hiring', 'Report a Malpractice Incident in Firing', 'Others',
    ,'Voter Registration', 'TAX', 'Services', 'Registrations and Licenses', 'Policies and Procedures', 'Patta', 'Land Registrations', 'Khata', 'Domicile and Residence', 'Death and Bereavement', 'Certificates', 'Caste, Community and Income', 'Building and Housing', 'Birth, Family and Care', 'Aadhaar Card', 'Other'
    ,'Policies and Procedures', 'Passport Status and Delivery', 'OCI and PIO', 'Issue and Renewal of Passport', 'Certificates', 'Others',
    ,'Pension Transfers', 'Pension Settlements', 'Pension Processing', 'Others',
    ,'Verification and Certificates', 'Traffic Fines, Penalties, Rules', 'Registrations and Licenses', 'Policies and Procedures', 'FIR and Complaints', 'Others',
    ,'Savings Schemes', 'Post and Parcel', 'Policies and Procedures', 'Money Order and Passbook', 'Others',
    ,'Policies and Procedures', 'Other',
    ,'Rules and Regulations', 'Policies and Procedures', 'Government Personnel', 'Certificates', 'Others',
    ,'Policies and Procedures', 'Government Personnel', 'Others',
    ,'Policies and Procedures', 'Transport of Luggage and Goods', 'Ticket and Seat Related', 'Railway Services', 'Fines Penalties', 'Others',
    ,'Religious Institutions', 'Others',
    ,'Caste, Community and Income', 'Certificates', 'Land Registration', 'Others',
    ,'Rules and Regulations', 'Housing', 'Others',
    ,'Registrations and licenses', 'Government Schemes', 'Certificates', 'Others',
    ,'Registrations and licenses', 'Property Registrations', 'Policies and Procedures', 'Marriage Certificate and Registration', 'Khata', 'Certificates', 'Others',
    ,'Telephone and Internet Connection', 'Bills and Payment', 'Others',
    ,'Vehicle Insurance', 'Vehicle Fitness', 'Traffic Fines, Penalties, Rules', 'Tax and Permits', 'Services', 'Public Transport', 'Number Plates and Vehicle Registration', 'Driving Licenses and Tests', 'Driving and Transport Business', 'Others',
    ,'Services', 'Registrations and licenses', 'Policies and Procedures', 'Land Related', 'Certificates', 'Building and Housing', 'Others',
    ,'Water Supply', 'Water Meter', 'Water Connection', 'Sewage Connection', 'Services', 'Rules and Regulations', 'Rainwater Harvesting', 'Borewells', 'Bills and Payment',
    ,'Others'
]