import React, { Component } from 'react';
import { View, Pressable, Text, Dimensions, StyleSheet, FlatList} from 'react-native';
import { TextInput } from 'react-native-paper';

const windowWidth = Dimensions.get('screen').width
const info = {
    city: ""
}
const Item = ({item, onSelect})=>(
    <Pressable style={styles.ItemContainer} hitSlop={8} onPress={()=>{
        info.city=item
        onSelect(item);
        }}>
        <Text style={styles.itemLabel}>
            {item}
        </Text>
    </Pressable>
)

class CityList extends Component {

    constructor(props){
        super(props)
        this.state = {
            query: '',
            focus: false
        }
    }

    filterSearch(query){
        let data = Cities.filter((city)=>{
            return city.title.toLowerCase().includes(query.toString().toLowerCase())
        })
        return data
    }

    selectCity(city){
        this.setState({query: city, focus: false });
        this.props.onSelect(city);
    }

    renderItem=({item})=>(
        <Item item={item.title} onSelect = {this.selectCity.bind(this)}/>
    )

  render() {
      let data = [];      
      if (this.state.query.length > 0) {
        data = this.filterSearch(this.state.query)
      }
        return (
            <View style={styles.listContainer }>
                <TextInput
                    onFocus={()=>{
                        this.setState({focus: true})
                        this.setState({query: ''})
                        }}
                    value={this.state.query}
                    mode='outlined'
                    label='Which city?'
                    style={ styles.input }
                    onChangeText={(txt)=>this.setState({query: txt})}
                />
                {  
                    (this.state.focus && this.state.query.length > 0  && data.length>0) ? 
                    (
                            <View style={{height: 210}}>
                                <FlatList
                                    style={styles.flatlist}
                                    data={ data }
                                    renderItem={ this.renderItem }
                                />
                            </View>

                    )
                    :
                    (
                        <></>
                    )
                }
            </View>

        );
    }
}

export default CityList;

const styles = StyleSheet.create({
    input:{
        margin: 10,
        marginBottom: 4,
        height: 40,
        width: Dimensions.get('window').width * 0.9
    },
    listConstainer:{
        flex:1,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        height: 90,
        width: windowWidth*0.9,
    },
    ItemContainer:{
        alignSelf: 'center',
        padding: 9,
        borderBottomWidth: 0.5,
        width: windowWidth * 0.79,
        backgroundColor: "rgba(246,239,242,0.5)",
    },
    flatlist: {
        flex: 1,
        alignSelf: 'center',
        borderWidth: 0.5,
        borderColor: "rgba(134,141,141,1)",
        borderRadius: 10,
        width: windowWidth * 0.8,
    },
    itemLabel:{
        alignSelf: 'center',
        fontSize: 14
    }
})

const Cities =[

    { 'value': 922, title: 'Abhayapuri' },
    { 'value': 1412, title: 'Abohar' },
    { 'value': 1600, title: 'Achhnera' },
    { 'value': 1601, title: 'Adari' },
    { 'value': 774, title: 'Adilabad' },
    { 'value': 1161, title: 'Adityapur' },
    { 'value': 775, title: 'Adoni' },
    { 'value': 1801, title: 'Adra' },
    { 'value': 1591, title: 'Agartala' },
    { 'value': 1602, title: 'Agra' },
    { 'value': 1307, title: 'Ahmadnagar' },
    { 'value': 1090, title: 'Ahmedabad' },
    { 'value': 1091, title: 'Ahwa' },
    { 'value': 1353, title: 'Aizawl' },
    { 'value': 1417, title: 'Ajmer' },
    { 'value': 1295, title: 'Akola' },
    { 'value': 1219, title: 'Alappuzha' },
    { 'value': 1603, title: 'Aligarh' },
    { 'value': 1802, title: 'Alipurduar' },
    { 'value': 1604, title: 'Allahabad' },
    { 'value': 1238, title: 'Alleppey' },
    { 'value': 1773, title: 'Almora' },
    { 'value': 1246, title: 'Aluva' },
    { 'value': 1418, title: 'Alwar' },
    { 'value': 1239, title: 'Alwaye' },
    { 'value': 776, title: 'Amadalavalasa' },
    { 'value': 777, title: 'Amalapuram' },
    { 'value': 996, title: 'Amarpur' },
    { 'value': 1114, title: 'Ambala' },
    { 'value': 1582, title: 'Ambattur' },
    { 'value': 1748, title: 'Ambedkar Nagar' },
    { 'value': 1077, title: 'Ambikapur' },
    { 'value': 778, title: 'Ameenapuram' },
    { 'value': 1749, title: 'Amethi' },
    { 'value': 923, title: 'Amguri' },
    { 'value': 1247, title: 'Amini' },
    { 'value': 1079, title: 'Amli' },
    { 'value': 1308, title: 'Amravati' },
    { 'value': 1092, title: 'Amreli' },
    { 'value': 1409, title: 'Amritsar' },
    { 'value': 1605, title: 'Amroha' },
    { 'value': 779, title: 'Anakapalle' },
    { 'value': 1093, title: 'Anand' },
    { 'value': 924, title: 'Anandnagaar' },
    { 'value': 780, title: 'Anantapur' },
    { 'value': 1147, title: 'Anantnag' },
    { 'value': 1358, title: 'Anugul' },
    { 'value': 1452, title: 'Arakkonam' },
    { 'value': 1803, title: 'Arambagh' },
    { 'value': 960, title: 'Araria' },
    { 'value': 1068, title: 'Araria' },
    { 'value': 1453, title: 'Arcot' },
    { 'value': 997, title: 'Areraj' },
    { 'value': 1583, title: 'Ariyalur' },
    { 'value': 998, title: 'Arrah' },
    { 'value': 1454, title: 'Aruppukkottai' },
    { 'value': 999, title: 'Arwal' },
    { 'value': 1804, title: 'Asansol' },
    { 'value': 1000, title: 'Asarganj' },
    { 'value': 1750, title: 'Auraiya' },
    { 'value': 1001, title: 'Aurangabad' },
    { 'value': 1309, title: 'Aurangabad' },
    { 'value': 1584, title: 'Avadi' },
    { 'value': 1606, title: 'Azamgarh' },
    { 'value': 781, title: 'Badepalle' },
    { 'value': 1148, title: 'Badgam' },
    { 'value': 1592, title: 'Badharghat' },
    { 'value': 1002, title: 'Bagaha' },
    { 'value': 1186, title: 'Bagalkot' },
    { 'value': 1774, title: 'Bageshwar' },
    { 'value': 1751, title: 'Baghpat' },
    { 'value': 1003, title: 'Bahadurganj' },
    { 'value': 1805, title: 'Baharampur' },
    { 'value': 1607, title: 'Bahraich' },
    { 'value': 1004, title: 'Bairgania' },
    { 'value': 1005, title: 'Bakhtiarpur' },
    { 'value': 1250, title: 'Balaghat' },
    { 'value': 1359, title: 'Balangir' },
    { 'value': 1360, title: 'Baleshwar' },
    { 'value': 1608, title: 'Ballia' },
    { 'value': 1806, title: 'Bally' },
    { 'value': 1609, title: 'Balrampur' },
    { 'value': 1807, title: 'Balurghat' },
    { 'value': 1094, title: 'Banas Kantha' },
    { 'value': 1610, title: 'Banda' },
    { 'value': 1187, title: 'Bangalore' },
    { 'value': 782, title: 'Banganapalle' },
    { 'value': 1213, title: 'Bangarapet' },
    { 'value': 961, title: 'Banka' },
    { 'value': 1808, title: 'Bankura' },
    { 'value': 1006, title: 'Banmankhi Bazar' },
    { 'value': 1419, title: 'Banswara' },
    { 'value': 783, title: 'Bapatla' },
    { 'value': 1752, title: 'Barabanki' },
    { 'value': 1007, title: 'Barahiya' },
    { 'value': 1809, title: 'Barakar' },
    { 'value': 1149, title: 'Baramula' },
    { 'value': 1420, title: 'Baran' },
    { 'value': 995, title: 'Baranui' },
    { 'value': 1810, title: 'Barasat' },
    { 'value': 1008, title: 'Barauli' },
    { 'value': 1009, title: 'Barbigha' },
    { 'value': 1811, title: 'Bardhaman' },
    { 'value': 1611, title: 'Bareilly' },
    { 'value': 1361, title: 'Bargarh' },
    { 'value': 1010, title: 'Barh' },
    { 'value': 1362, title: 'Baripada' },
    { 'value': 1421, title: 'Barmer' },
    { 'value': 1416, title: 'Barnala' },
    { 'value': 925, title: 'Barpeta' },
    { 'value': 926, title: 'Barpeta Road' },
    { 'value': 1812, title: 'Barrackpur' },
    { 'value': 1251, title: 'Barwani' },
    { 'value': 1753, title: 'Basti' },
    { 'value': 1411, title: 'Batala' },
    { 'value': 1392, title: 'Bathinda' },
    { 'value': 1363, title: 'Baudh' },
    { 'value': 1775, title: 'Bazpur' },
    { 'value': 1298, title: 'Beed' },
    { 'value': 962, title: 'Begusarai' },
    { 'value': 1011, title: 'Behea' },
    { 'value': 1188, title: 'Belgaum' },
    { 'value': 784, title: 'Bellampalle' },
    { 'value': 1189, title: 'Bellary' },
    { 'value': 1776, title: 'Berinag' },
    { 'value': 785, title: 'Bethamcherla' },
    { 'value': 1012, title: 'Bettiah' },
    { 'value': 1252, title: 'Betul' },
    { 'value': 972, title: 'Bhabua' },
    { 'value': 786, title: 'Bhadrachalam' },
    { 'value': 1364, title: 'Bhadrak' },
    { 'value': 963, title: 'Bhagalpur' },
    { 'value': 1013, title: 'Bhagalpur' },
    { 'value': 787, title: 'Bhainsa' },
    { 'value': 1296, title: 'Bhandara' },
    { 'value': 1422, title: 'Bharatpur' },
    { 'value': 1612, title: 'Bharthana' },
    { 'value': 1095, title: 'Bharuch' },
    { 'value': 1858, title: 'Bhatpara' },
    { 'value': 1455, title: 'Bhavani' },
    { 'value': 1096, title: 'Bhavnagar' },
    { 'value': 788, title: 'Bheemunipatnam' },
    { 'value': 1071, title: 'Bhilai' },
    { 'value': 1423, title: 'Bhilwara' },
    { 'value': 789, title: 'Bhimavaram' },
    { 'value': 1253, title: 'Bhind' },
    { 'value': 1297, title: 'Bhiwandi' },
    { 'value': 1115, title: 'Bhiwani' },
    { 'value': 964, title: 'Bhojpur' },
    { 'value': 790, title: 'Bhongir' },
    { 'value': 1254, title: 'Bhopal' },
    { 'value': 1365, title: 'Bhubaneswar' },
    { 'value': 1097, title: 'Bhuj' },
    { 'value': 1338, title: 'Bhusaval' },
    { 'value': 1190, title: 'Bidar' },
    { 'value': 1813, title: 'Bidhan Nagar' },
    { 'value': 1014, title: 'Bihar Sharif' },
    { 'value': 1191, title: 'Bijapur' },
    { 'value': 1613, title: 'Bijnaur' },
    { 'value': 1424, title: 'Bikaner' },
    { 'value': 1015, title: 'Bikramganj' },
    { 'value': 927, title: 'Bilasipara' },
    { 'value': 1072, title: 'Bilaspur' },
    { 'value': 1134, title: 'Bilaspur' },
    { 'value': 1303, title: 'Bina' },
    { 'value': 1859, title: 'Birbhum' },
    { 'value': 1342, title: 'Bishnupur' },
    { 'value': 791, title: 'Bobbili' },
    { 'value': 1016, title: 'Bodh Gaya' },
    { 'value': 792, title: 'Bodhan' },
    { 'value': 1162, title: 'Bokaro' },
    { 'value': 921, title: 'Bomdila' },
    { 'value': 928, title: 'Bongaigaon' },
    { 'value': 1614, title: 'Budaun' },
    { 'value': 1615, title: 'Bulandshahr' },
    { 'value': 1299, title: 'Buldana' },
    { 'value': 1425, title: 'Bundi' },
    { 'value': 1860, title: 'Burdwan' },
    { 'value': 1249, title: 'Burhanpur' },
    { 'value': 965, title: 'Buxar' },
    { 'value': 1240, title: 'Calicut' },
    { 'value': 1616, title: 'Chakeri' },
    { 'value': 1192, title: 'Chamarajanagar' },
    { 'value': 1135, title: 'Chamba' },
    { 'value': 1777, title: 'Chamba' },
    { 'value': 1778, title: 'Champawat' },
    { 'value': 1355, title: 'Champhai' },
    { 'value': 1017, title: 'Chandan Bara' },
    { 'value': 1754, title: 'Chandauli' },
    { 'value': 1617, title: 'Chandausi' },
    { 'value': 1343, title: 'Chandel' },
    { 'value': 1069, title: 'Chandigarh' },
    { 'value': 1300, title: 'Chandrapur' },
    { 'value': 1018, title: 'Chanpatia' },
    { 'value': 793, title: 'Chapirevula' },
    { 'value': 1618, title: 'Charkhari' },
    { 'value': 1163, title: 'Chas' },
    { 'value': 1164, title: 'Chatra' },
    { 'value': 1779, title: 'Chaukori' },
    { 'value': 1456, title: 'Chengalpattu' },
    { 'value': 1457, title: 'Chennai' },
    { 'value': 966, title: 'Chhapra' },
    { 'value': 1255, title: 'Chhatarpur' },
    { 'value': 1256, title: 'Chhindwara' },
    { 'value': 1216, title: 'Chikballapur' },
    { 'value': 1193, title: 'Chikmagalur' },
    { 'value': 794, title: 'Chilakaluripet' },
    { 'value': 1458, title: 'Chinna salem' },
    { 'value': 1814, title: 'Chinsura' },
    { 'value': 795, title: 'Chirala' },
    { 'value': 1194, title: 'Chitradurga' },
    { 'value': 1306, title: 'Chitrakoot' },
    { 'value': 1861, title: 'Chittaranjan' },
    { 'value': 1426, title: 'Chittaurgarh' },
    { 'value': 796, title: 'Chittoor' },
    { 'value': 1344, title: 'Churachandpur' },
    { 'value': 1427, title: 'Churu' },
    { 'value': 1241, title: 'Cochin' },
    { 'value': 1459, title: 'Coimbatore' },
    { 'value': 1019, title: 'Colgong' },
    { 'value': 1815, title: 'Contai' },
    { 'value': 1816, title: 'Cooch Behar' },
    { 'value': 1460, title: 'Coonoor' },
    { 'value': 1461, title: 'Cuddalore' },
    { 'value': 797, title: 'Cuddapah' },
    { 'value': 1366, title: 'Cuttack' },
    { 'value': 1619, title: 'Dadri' },
    { 'value': 1817, title: 'Dalkhola' },
    { 'value': 1020, title: 'Dalsinghsarai' },
    { 'value': 1081, title: 'Daman' },
    { 'value': 1257, title: 'Damoh' },
    { 'value': 967, title: 'Darbhanga' },
    { 'value': 1818, title: 'Darjeeling' },
    { 'value': 1258, title: 'Datia' },
    { 'value': 1021, title: 'Daudnagar' },
    { 'value': 1428, title: 'Dausa' },
    { 'value': 1195, title: 'Davanagere' },
    { 'value': 1367, title: 'Debagarh' },
    { 'value': 1780, title: 'Dehradun' },
    { 'value': 1022, title: 'Dehri-on-Sone' },
    { 'value': 1165, title: 'Deoghar' },
    { 'value': 1620, title: 'Deoria' },
    { 'value': 798, title: 'Devarakonda' },
    { 'value': 1259, title: 'Dewas' },
    { 'value': 1621, title: 'Dhampur' },
    { 'value': 1078, title: 'Dhamtari' },
    { 'value': 1166, title: 'Dhanbad' },
    { 'value': 1260, title: 'Dhar' },
    { 'value': 1593, title: 'Dharmanagar' },
    { 'value': 1462, title: 'Dharmapuri' },
    { 'value': 799, title: 'Dharmavaram' },
    { 'value': 1196, title: 'Dharwad' },
    { 'value': 1214, title: 'Dharwar' },
    { 'value': 1429, title: 'Dhaulpur' },
    { 'value': 929, title: 'Dhekiajuli' },
    { 'value': 1368, title: 'Dhenkanal' },
    { 'value': 930, title: 'Dhubri' },
    { 'value': 1301, title: 'Dhule' },
    { 'value': 1819, title: 'Dhulian' },
    { 'value': 931, title: 'Dibrugarh' },
    { 'value': 932, title: 'Digboi' },
    { 'value': 1023, title: 'Dighwara' },
    { 'value': 1356, title: 'Dimapur' },
    { 'value': 1463, title: 'Dindigul' },
    { 'value': 1261, title: 'Dindori' },
    { 'value': 933, title: 'Diphu' },
    { 'value': 934, title: 'Dispur' },
    { 'value': 1082, title: 'Diu' },
    { 'value': 1150, title: 'Doda' },
    { 'value': 1098, title: 'Dohad' },
    { 'value': 935, title: 'Duliajan Oil Town' },
    { 'value': 1820, title: 'Dumdum' },
    { 'value': 1167, title: 'Dumka' },
    { 'value': 1024, title: 'Dumraon' },
    { 'value': 1430, title: 'Dungarpur' },
    { 'value': 1821, title: 'Durgapur' },
    { 'value': 1262, title: 'East Nimar/Khandwa' },
    { 'value': 800, title: 'Eluru' },
    { 'value': 1822, title: 'English Bazar(Malda)' },
    { 'value': 1220, title: 'Ernakulam' },
    { 'value': 1464, title: 'Erode' },
    { 'value': 1622, title: 'Etah' },
    { 'value': 1623, title: 'Etawah' },
    { 'value': 1624, title: 'Faizabad' },
    { 'value': 1116, title: 'Faridabad' },
    { 'value': 1393, title: 'Faridkot' },
    { 'value': 801, title: 'Farooqnagar' },
    { 'value': 1625, title: 'Farrukhabad' },
    { 'value': 1117, title: 'Fatehabad' },
    { 'value': 1626, title: 'Fatehabad' },
    { 'value': 1627, title: 'Fatehgarh' },
    { 'value': 1394, title: 'Fatehgarh Sahib' },
    { 'value': 1630, title: 'Fatehpur' },
    { 'value': 1628, title: 'Fatehpur Chaurasi' },
    { 'value': 1629, title: 'Fatehpur Sikri' },
    { 'value': 1025, title: 'Fatwah' },
    { 'value': 1631, title: 'Firozabad' },
    { 'value': 1395, title: 'Firozpur' },
    { 'value': 1026, title: 'Forbesganj' },
    { 'value': 1197, title: 'Gadag' },
    { 'value': 1302, title: 'Gadchiroli' },
    { 'value': 802, title: 'Gadwal' },
    { 'value': 1369, title: 'Gajapati' },
    { 'value': 1099, title: 'Gandhidham' },
    { 'value': 1100, title: 'Gandhinagar' },
    { 'value': 1431, title: 'Ganganagar' },
    { 'value': 1450, title: 'Gangtok' },
    { 'value': 1370, title: 'Ganjam' },
    { 'value': 1168, title: 'Garhwa' },
    { 'value': 936, title: 'Gauripur' },
    { 'value': 968, title: 'Gaya' },
    { 'value': 1632, title: 'Ghatampur' },
    { 'value': 1633, title: 'Ghaziabad' },
    { 'value': 1634, title: 'Ghazipur' },
    { 'value': 1465, title: 'Gingee' },
    { 'value': 1169, title: 'Giridih' },
    { 'value': 937, title: 'Goalpara' },
    { 'value': 1466, title: 'Gobichettipalayam' },
    { 'value': 1170, title: 'Godda' },
    { 'value': 1027, title: 'Gogri Jamalpur' },
    { 'value': 938, title: 'Golaghat' },
    { 'value': 1755, title: 'Gonda' },
    { 'value': 1341, title: 'Gondiya' },
    { 'value': 803, title: 'Gooty' },
    { 'value': 969, title: 'Gopalganj' },
    { 'value': 1635, title: 'Gorakhpur' },
    { 'value': 1636, title: 'Greater Noida' },
    { 'value': 1467, title: 'Gudalur' },
    { 'value': 1468, title: 'Gudalur' },
    { 'value': 1469, title: 'Gudalur' },
    { 'value': 804, title: 'Gudivada' },
    { 'value': 805, title: 'Gudur' },
    { 'value': 1198, title: 'Gulbarga' },
    { 'value': 1171, title: 'Gumla' },
    { 'value': 1263, title: 'Guna' },
    { 'value': 806, title: 'Guntakal' },
    { 'value': 807, title: 'Guntur' },
    { 'value': 1396, title: 'Gurdaspur' },
    { 'value': 1118, title: 'Gurgaon' },
    { 'value': 939, title: 'Guwahati' },
    { 'value': 1264, title: 'Gwalior' },
    { 'value': 1304, title: 'Habibganj' },
    { 'value': 1799, title: 'Haldwani' },
    { 'value': 1136, title: 'Hamirpur' },
    { 'value': 1432, title: 'Hanumangarh' },
    { 'value': 1265, title: 'Harda' },
    { 'value': 1756, title: 'Hardoi' },
    { 'value': 1757, title: 'Haridwar' },
    { 'value': 1199, title: 'Hassan' },
    { 'value': 1758, title: 'Hathras' },
    { 'value': 1200, title: 'Haveri' },
    { 'value': 1172, title: 'Hazaribagh' },
    { 'value': 911, title: 'Hindupur' },
    { 'value': 1310, title: 'Hingoli' },
    { 'value': 1119, title: 'Hisar' },
    { 'value': 1266, title: 'Hoshangabad' },
    { 'value': 1397, title: 'Hoshiarpur' },
    { 'value': 1862, title: 'Howrah' },
    { 'value': 1215, title: 'Hubli' },
    { 'value': 1863, title: 'Hugli' },
    { 'value': 910, title: 'Hyderabad' },
    { 'value': 808, title: 'Ichchapuram' },
    { 'value': 1221, title: 'Idukki' },
    { 'value': 1345, title: 'Imphal' },
    { 'value': 1267, title: 'Indore' },
    { 'value': 1594, title: 'Indranagar' },
    { 'value': 1028, title: 'Islampur' },
    { 'value': 1823, title: 'Islampur' },
    { 'value': 917, title: 'Itanagar' },
    { 'value': 1305, title: 'Itarasi' },
    { 'value': 1268, title: 'Jabalpur' },
    { 'value': 1371, title: 'Jagatsinghapur' },
    { 'value': 1076, title: 'Jagdalpur' },
    { 'value': 1029, title: 'Jagdispur' },
    { 'value': 809, title: 'Jaggaiahpet' },
    { 'value': 810, title: 'Jagtial' },
    { 'value': 1433, title: 'Jaipur' },
    { 'value': 1637, title: 'Jais' },
    { 'value': 1434, title: 'Jaisalmer' },
    { 'value': 1372, title: 'Jajapur' },
    { 'value': 1638, title: 'Jajmau' },
    { 'value': 1398, title: 'Jalandhar' },
    { 'value': 1759, title: 'Jalaun' },
    { 'value': 1311, title: 'Jalgaon' },
    { 'value': 1312, title: 'Jalna' },
    { 'value': 1435, title: 'Jalor' },
    { 'value': 1824, title: 'Jalpaiguri' },
    { 'value': 1030, title: 'Jamalpur' },
    { 'value': 811, title: 'Jammalamadugu' },
    { 'value': 1151, title: 'Jammu' },
    { 'value': 1101, title: 'Jamnagar' },
    { 'value': 1173, title: 'Jamshedpur' },
    { 'value': 1174, title: 'Jamtara' },
    { 'value': 970, title: 'Jamui' },
    { 'value': 812, title: 'Jangaon' },
    { 'value': 1781, title: 'Jaspur' },
    { 'value': 1639, title: 'Jaunpur' },
    { 'value': 1470, title: 'Jayankondam' },
    { 'value': 971, title: 'Jehanabad' },
    { 'value': 1269, title: 'Jhabua' },
    { 'value': 1031, title: 'Jhajha' },
    { 'value': 1120, title: 'Jhajjar' },
    { 'value': 1436, title: 'Jhalawar' },
    { 'value': 1032, title: 'Jhanjharpur' },
    { 'value': 1640, title: 'Jhansi' },
    { 'value': 1825, title: 'Jhargram' },
    { 'value': 1373, title: 'Jharsuguda' },
    { 'value': 1437, title: 'Jhunjhunun' },
    { 'value': 1121, title: 'Jind' },
    { 'value': 1438, title: 'Jodhpur' },
    { 'value': 1033, title: 'Jogabani' },
    { 'value': 1595, title: 'Jogendranagar' },
    { 'value': 940, title: 'Jorhat' },
    { 'value': 1102, title: 'Junagadh' },
    { 'value': 1760, title: 'Jyotiba Phule Nagar' },
    { 'value': 813, title: 'Kadapa' },
    { 'value': 814, title: 'Kadiri' },
    { 'value': 815, title: 'Kagaznagar' },
    { 'value': 1596, title: 'Kailasahar' },
    { 'value': 1122, title: 'Kaithal' },
    { 'value': 816, title: 'Kakinada' },
    { 'value': 1374, title: 'Kalahandi' },
    { 'value': 1826, title: 'Kalimpong' },
    { 'value': 1133, title: 'Kalka' },
    { 'value': 1641, title: 'Kalpi' },
    { 'value': 1313, title: 'Kalyan' },
    { 'value': 817, title: 'Kalyandurg' },
    { 'value': 818, title: 'Kamareddy' },
    { 'value': 1471, title: 'Kanchipuram' },
    { 'value': 1782, title: 'Kanda' },
    { 'value': 1375, title: 'Kandhamal/Phulbani' },
    { 'value': 819, title: 'Kandukur' },
    { 'value': 1137, title: 'Kangra' },
    { 'value': 1761, title: 'Kannauj' },
    { 'value': 1581, title: 'Kanniyakumari' },
    { 'value': 1222, title: 'Kannur' },
    { 'value': 1642, title: 'Kanpur' },
    { 'value': 1034, title: 'Kanti' },
    { 'value': 1399, title: 'Kapurthala' },
    { 'value': 1472, title: 'Karaikudi' },
    { 'value': 1439, title: 'Karauli' },
    { 'value': 1152, title: 'Kargil' },
    { 'value': 941, title: 'Karimganj' },
    { 'value': 820, title: 'Karimnagar' },
    { 'value': 1123, title: 'Karnal' },
    { 'value': 1474, title: 'Karungal' },
    { 'value': 1473, title: 'Karur' },
    { 'value': 1201, title: 'Karwar' },
    { 'value': 1223, title: 'Kasaragod' },
    { 'value': 1783, title: 'Kashipur' },
    { 'value': 1800, title: 'Kathgodam' },
    { 'value': 1153, title: 'Kathua' },
    { 'value': 973, title: 'Katihar' },
    { 'value': 1270, title: 'Katni' },
    { 'value': 1585, title: 'Katpadi' },
    { 'value': 1762, title: 'Kaushambi' },
    { 'value': 821, title: 'Kavali' },
    { 'value': 1248, title: 'Kavaratti' },
    { 'value': 1590, title: 'Kayalpattinam' },
    { 'value': 912, title: 'Kazipet' },
    { 'value': 1376, title: 'Kendrapara' },
    { 'value': 1377, title: 'Kendujhar' },
    { 'value': 974, title: 'Khagaria' },
    { 'value': 822, title: 'Khammam' },
    { 'value': 1414, title: 'Khanna' },
    { 'value': 1035, title: 'Kharagpur' },
    { 'value': 1827, title: 'Kharagpur' },
    { 'value': 1643, title: 'Kheri' },
    { 'value': 1378, title: 'Khordha' },
    { 'value': 1597, title: 'Khowai' },
    { 'value': 1784, title: 'Kichha' },
    { 'value': 1138, title: 'Kinnaur' },
    { 'value': 975, title: 'Kishanganj' },
    { 'value': 1224, title: 'Kochi' },
    { 'value': 823, title: 'Kodad' },
    { 'value': 1202, title: 'Kodagu' },
    { 'value': 1175, title: 'Kodarma' },
    { 'value': 1357, title: 'Kohima' },
    { 'value': 942, title: 'Kokrajhar' },
    { 'value': 1203, title: 'Kolar' },
    { 'value': 1314, title: 'Kolhapur' },
    { 'value': 1828, title: 'Kolkata' },
    { 'value': 1225, title: 'Kollam' },
    { 'value': 1475, title: 'Kollankodu' },
    { 'value': 1829, title: 'Konnagar' },
    { 'value': 1204, title: 'Koppal' },
    { 'value': 1379, title: 'Koraput' },
    { 'value': 824, title: 'Koratla' },
    { 'value': 1073, title: 'Korba' },
    { 'value': 1440, title: 'Kota' },
    { 'value': 1785, title: 'Kotdwara' },
    { 'value': 825, title: 'Kothagudem' },
    { 'value': 826, title: 'Kothapeta' },
    { 'value': 1226, title: 'Kottayam' },
    { 'value': 827, title: 'Kovvur' },
    { 'value': 1227, title: 'Kozhikode' },
    { 'value': 1586, title: 'Krishnagiri' },
    { 'value': 1830, title: 'Krishnanagar' },
    { 'value': 1139, title: 'Kullu' },
    { 'value': 1644, title: 'Kulpahar' },
    { 'value': 1864, title: 'Kulti' },
    { 'value': 1154, title: 'Kupwara' },
    { 'value': 828, title: 'Kurnool' },
    { 'value': 1124, title: 'Kurukshetra' },
    { 'value': 1763, title: 'Kushinagar' },
    { 'value': 829, title: 'Kyathampalle' },
    { 'value': 1645, title: 'Laharpur' },
    { 'value': 1140, title: 'Lahul & Spiti' },
    { 'value': 1646, title: 'Lakhimpur' },
    { 'value': 1764, title: 'Lakhimpur Kheri' },
    { 'value': 976, title: 'Lakhisarai' },
    { 'value': 1647, title: 'Lal Gopalganj Nindaura' },
    { 'value': 1036, title: 'Lalganj' },
    { 'value': 1649, title: 'Lalganj' },
    { 'value': 1476, title: 'Lalgudi' },
    { 'value': 1648, title: 'Lalitpur' },
    { 'value': 943, title: 'Lanka' },
    { 'value': 1650, title: 'Lar' },
    { 'value': 1176, title: 'Latehar' },
    { 'value': 1318, title: 'Latur' },
    { 'value': 1155, title: 'Leh (Ladakh)' },
    { 'value': 1177, title: 'Lohardaga' },
    { 'value': 1651, title: 'Loni' },
    { 'value': 1652, title: 'Lucknow' },
    { 'value': 1400, title: 'Ludhiana' },
    { 'value': 944, title: 'Lumding' },
    { 'value': 1354, title: 'Lunglei' },
    { 'value': 830, title: 'Macherla' },
    { 'value': 831, title: 'Machilipatnam' },
    { 'value': 832, title: 'Madanapalle' },
    { 'value': 1085, title: 'Madgaon' },
    { 'value': 977, title: 'Madhepura' },
    { 'value': 978, title: 'Madhubani' },
    { 'value': 1477, title: 'Madurai' },
    { 'value': 1449, title: 'Mahamandir' },
    { 'value': 1037, title: 'Maharajganj' },
    { 'value': 1765, title: 'Maharajganj' },
    { 'value': 833, title: 'Mahbubnagar' },
    { 'value': 1125, title: 'Mahendragarh' },
    { 'value': 1103, title: 'Mahesana' },
    { 'value': 1865, title: 'Maheshtala' },
    { 'value': 1038, title: 'Mahnar Bazar' },
    { 'value': 1653, title: 'Mahoba' },
    { 'value': 1831, title: 'Mainaguri' },
    { 'value': 1766, title: 'Mainpuri' },
    { 'value': 1039, title: 'Makhdumpur' },
    { 'value': 1832, title: 'Mal' },
    { 'value': 1228, title: 'Malappuram' },
    { 'value': 1866, title: 'Maldah' },
    { 'value': 1315, title: 'Malegaon' },
    { 'value': 1413, title: 'Malerkotla' },
    { 'value': 1380, title: 'Malkangiri' },
    { 'value': 834, title: 'Mancherial' },
    { 'value': 835, title: 'Mandamarri' },
    { 'value': 836, title: 'Mandapeta' },
    { 'value': 1141, title: 'Mandi' },
    { 'value': 1271, title: 'Mandla' },
    { 'value': 1272, title: 'Mandsaur' },
    { 'value': 1205, title: 'Mandya' },
    { 'value': 1040, title: 'Maner' },
    { 'value': 837, title: 'Mangalagiri' },
    { 'value': 945, title: 'Mangaldoi' },
    { 'value': 1206, title: 'Mangalore' },
    { 'value': 1786, title: 'Manglaur' },
    { 'value': 1178, title: 'Mango' },
    { 'value': 1041, title: 'Manihari' },
    { 'value': 1229, title: 'Manjeri' },
    { 'value': 946, title: 'Mankachar' },
    { 'value': 1339, title: 'Manmad' },
    { 'value': 1401, title: 'Mansa' },
    { 'value': 838, title: 'Manuguru' },
    { 'value': 1088, title: 'Margao' },
    { 'value': 947, title: 'Margherita' },
    { 'value': 1042, title: 'Marhaura' },
    { 'value': 948, title: 'Mariani' },
    { 'value': 949, title: 'Marigaon' },
    { 'value': 839, title: 'Markapur' },
    { 'value': 1043, title: 'Masaurhi' },
    { 'value': 1833, title: 'Mathabhanga' },
    { 'value': 1654, title: 'Mathura' },
    { 'value': 1767, title: 'Mau' },
    { 'value': 1351, title: 'Mawlai' },
    { 'value': 1381, title: 'Mayurbhanj' },
    { 'value': 840, title: 'Medak' },
    { 'value': 1834, title: 'Medinipur' },
    { 'value': 1655, title: 'Meerut' },
    { 'value': 1835, title: 'Memari' },
    { 'value': 1316, title: 'Mira Bhayandar' },
    { 'value': 1044, title: 'Mirganj' },
    { 'value': 841, title: 'Miryalaguda' },
    { 'value': 1656, title: 'Mirzapur' },
    { 'value': 1657, title: 'Modinagar' },
    { 'value': 1402, title: 'Moga' },
    { 'value': 842, title: 'Mogalthur' },
    { 'value': 1045, title: 'Mohania' },
    { 'value': 1046, title: 'Mokama' },
    { 'value': 1047, title: 'Mokameh' },
    { 'value': 1836, title: 'Monoharpur' },
    { 'value': 1658, title: 'Moradabad' },
    { 'value': 1273, title: 'Morena' },
    { 'value': 1084, title: 'Mormugao' },
    { 'value': 1048, title: 'Motihari' },
    { 'value': 1049, title: 'Motipur' },
    { 'value': 1403, title: 'Muktsar' },
    { 'value': 1317, title: 'Mumbai' },
    { 'value': 979, title: 'Munger' },
    { 'value': 1659, title: 'Muradnagar' },
    { 'value': 1050, title: 'Murliganj' },
    { 'value': 1837, title: 'Murshidabad' },
    { 'value': 1294, title: 'Murwara' },
    { 'value': 1787, title: 'Mussoorie' },
    { 'value': 1660, title: 'Muzaffarnagar' },
    { 'value': 980, title: 'Muzaffarpur' },
    { 'value': 1207, title: 'Mysore' },
    { 'value': 1838, title: 'Nabadwip' },
    { 'value': 1382, title: 'Nabarangapur' },
    { 'value': 1867, title: 'Nadia' },
    { 'value': 1104, title: 'Nadiad' },
    { 'value': 950, title: 'Nagaon' },
    { 'value': 1478, title: 'Nagapattinam' },
    { 'value': 843, title: 'Nagari' },
    { 'value': 844, title: 'Nagarkurnool' },
    { 'value': 1441, title: 'Nagaur' },
    { 'value': 1479, title: 'Nagercoil' },
    { 'value': 1661, title: 'Nagina' },
    { 'value': 1788, title: 'Nagla' },
    { 'value': 1319, title: 'Nagpur' },
    { 'value': 1142, title: 'Nahan' },
    { 'value': 918, title: 'Naharlagun' },
    { 'value': 1839, title: 'Naihati' },
    { 'value': 1789, title: 'Nainital' },
    { 'value': 1662, title: 'Najibabad' },
    { 'value': 1663, title: 'Nakur' },
    { 'value': 981, title: 'Nalanda' },
    { 'value': 951, title: 'Nalbari' },
    { 'value': 913, title: 'Nalgonda' },
    { 'value': 1480, title: 'Namagiripettai' },
    { 'value': 1481, title: 'Namakkal' },
    { 'value': 1320, title: 'Nanded' },
    { 'value': 1482, title: 'Nandivaram-Guduvancheri' },
    { 'value': 1321, title: 'Nandurbar' },
    { 'value': 845, title: 'Nandyal' },
    { 'value': 1483, title: 'Nanjikottai' },
    { 'value': 1664, title: 'Nanpara' },
    { 'value': 846, title: 'Narasapur' },
    { 'value': 847, title: 'Narasaraopet' },
    { 'value': 1665, title: 'Naraura' },
    { 'value': 848, title: 'Narayanpet' },
    { 'value': 1051, title: 'Narkatiaganj' },
    { 'value': 1274, title: 'Narsimhapur' },
    { 'value': 849, title: 'Narsipatnam' },
    { 'value': 1322, title: 'Nashik' },
    { 'value': 1484, title: 'Natham' },
    { 'value': 1052, title: 'Naugachhia' },
    { 'value': 1666, title: 'Naugawan Sadat' },
    { 'value': 1667, title: 'Nautanwa' },
    { 'value': 1323, title: 'Navi Mumbai' },
    { 'value': 1105, title: 'Navsari' },
    { 'value': 1668, title: 'Nawabganj' },
    { 'value': 982, title: 'Nawada' },
    { 'value': 1404, title: 'Nawanshahr' },
    { 'value': 1383, title: 'Nayagarh' },
    { 'value': 1275, title: 'Neemuch' },
    { 'value': 1669, title: 'Nehtaur' },
    { 'value': 1485, title: 'Nellikuppam' },
    { 'value': 850, title: 'Nellore' },
    { 'value': 1083, title: 'New Delhi' },
    { 'value': 1486, title: 'Neyveli' },
    { 'value': 851, title: 'Nidadavole' },
    { 'value': 852, title: 'Nirmal' },
    { 'value': 853, title: 'Nizamabad' },
    { 'value': 1670, title: 'Noida' },
    { 'value': 1053, title: 'Nokha' },
    { 'value': 1352, title: 'Nongthymmai' },
    { 'value': 1671, title: 'Noorpur' },
    { 'value': 952, title: 'North Lakhimpur' },
    { 'value': 1384, title: 'Nuapada' },
    { 'value': 854, title: 'Nuzvid' },
    {'value': 1487, title: "O' Valley"},
 { 'value': 1672, title: 'Obra' },
 { 'value': 1488, title: 'Oddanchatram' },
    { 'value': 855, title: 'Ongole' },
    { 'value': 1673, title: 'Orai' },
    { 'value': 1326, title: 'Osmanabad' },
    { 'value': 1489, title: 'P.N.Patti' },
    { 'value': 1490, title: 'Pacode' },
    { 'value': 1491, title: 'Padmanabhapuram' },
    { 'value': 1674, title: 'Padrauna' },
    { 'value': 1179, title: 'Pakaur' },
    { 'value': 856, title: 'Palacole' },
    { 'value': 1230, title: 'Palakkad' },
    { 'value': 1180, title: 'Palamu' },
    { 'value': 1492, title: 'Palani' },
    { 'value': 857, title: 'Palasa Kasibugga' },
    { 'value': 1242, title: 'Palghat' },
    { 'value': 1442, title: 'Pali' },
    { 'value': 1675, title: 'Palia Kalan' },
    { 'value': 1493, title: 'Palladam' },
    { 'value': 1494, title: 'Pallapatti' },
    { 'value': 1495, title: 'Pallikonda' },
    { 'value': 859, title: 'Palwancha' },
    { 'value': 1496, title: 'Panagudi' },
    { 'value': 1086, title: 'Panaji' },
    { 'value': 1126, title: 'Panchkula' },
    { 'value': 1840, title: 'Panchla' },
    { 'value': 1841, title: 'Pandua' },
    { 'value': 1868, title: 'Panihati' },
    { 'value': 1127, title: 'Panipat' },
    { 'value': 1276, title: 'Panna' },
    { 'value': 1497, title: 'Panruti' },
    { 'value': 1498, title: 'Paramakudi' },
    { 'value': 1499, title: 'Parangipettai' },
    { 'value': 1676, title: 'Parasi' },
    { 'value': 1327, title: 'Parbhani' },
    { 'value': 860, title: 'Parvathipuram' },
    { 'value': 1842, title: 'Paschim Punropara' },
    { 'value': 919, title: 'Pasighat' },
    { 'value': 1106, title: 'Patan' },
    { 'value': 1231, title: 'Pathanamthitta' },
    { 'value': 1405, title: 'Pathankot' },
    { 'value': 1406, title: 'Patiala' },
    { 'value': 983, title: 'Patna' },
    { 'value': 1500, title: 'Pattukkottai' },
    { 'value': 1790, title: 'Pauri' },
    { 'value': 861, title: 'Pedana' },
    { 'value': 862, title: 'Peddapuram' },
    { 'value': 1501, title: 'Perambalur' },
    { 'value': 1502, title: 'Peravurani' },
    { 'value': 1503, title: 'Periyakulam' },
    { 'value': 1504, title: 'Periyasemur' },
    { 'value': 1505, title: 'Pernampattu' },
    { 'value': 1415, title: 'Phagwara' },
    { 'value': 1677, title: 'Phulpur' },
    { 'value': 914, title: 'Piduguralla' },
    { 'value': 1678, title: 'Pihani' },
    { 'value': 1679, title: 'Pilibhit' },
    { 'value': 1680, title: 'Pilkhuwa' },
    { 'value': 1324, title: 'Pimpri-Chinchwad' },
    { 'value': 1054, title: 'Piro' },
    { 'value': 863, title: 'Pithapuram' },
    { 'value': 1791, title: 'Pithoragarh' },
    { 'value': 1506, title: 'Pollachi' },
    { 'value': 1507, title: 'Polur' },
    { 'value': 1087, title: 'Ponda' },
    { 'value': 1391, title: 'Pondicherry' },
    { 'value': 858, title: 'Pondur' },
    { 'value': 1232, title: 'Ponnani' },
    { 'value': 1508, title: 'Ponneri' },
    { 'value': 864, title: 'Ponnur' },
    { 'value': 1107, title: 'Porbandar' },
    { 'value': 773, title: 'Port Blair' },
    { 'value': 1681, title: 'Powayan' },
    { 'value': 1598, title: 'Pratapgarh' },
    { 'value': 865, title: 'Proddatur' },
    { 'value': 1509, title: 'Pudukkottai' },
    { 'value': 1510, title: 'Pudupattinam' },
    { 'value': 1682, title: 'Pukhrayan' },
    { 'value': 1511, title: 'Puliyankudi' },
    { 'value': 1156, title: 'Pulwama' },
    { 'value': 1157, title: 'Punch' },
    { 'value': 1325, title: 'Pune' },
    { 'value': 866, title: 'Punganur' },
    { 'value': 1512, title: 'Punjaipugalur' },
    { 'value': 1683, title: 'Puranpur' },
    { 'value': 1385, title: 'Puri' },
    { 'value': 984, title: 'Purnia' },
    { 'value': 1684, title: 'Purquazi' },
    { 'value': 1843, title: 'Purulia' },
    { 'value': 1685, title: 'Purwa' },
    { 'value': 915, title: 'Puttaparthi' },
    { 'value': 867, title: 'Puttur' },
    { 'value': 1686, title: 'Rae Bareli' },
    { 'value': 1055, title: 'Rafiganj' },
    { 'value': 1845, title: 'Raghunathganj' },
    { 'value': 1844, title: 'Raghunathpur' },
    { 'value': 1208, title: 'Raichur' },
    { 'value': 1846, title: 'Raiganj' },
    { 'value': 1075, title: 'Raigarh' },
    { 'value': 1070, title: 'Raipur' },
    { 'value': 1277, title: 'Raisen' },
    { 'value': 868, title: 'Rajahmundry' },
    { 'value': 869, title: 'Rajam' },
    { 'value': 870, title: 'Rajampet' },
    { 'value': 1513, title: 'Rajapalayam' },
    { 'value': 1158, title: 'Rajauri' },
    { 'value': 1278, title: 'Rajgarh' },
    { 'value': 1056, title: 'Rajgir' },
    { 'value': 1108, title: 'Rajkot' },
    { 'value': 1074, title: 'Rajnandgaon' },
    { 'value': 1869, title: 'Rajpur Sonarpur' },
    { 'value': 1443, title: 'Rajsamand' },
    { 'value': 871, title: 'Ramachandrapuram' },
    { 'value': 872, title: 'Ramagundam' },
    { 'value': 1514, title: 'Ramanathapuram' },
    { 'value': 1515, title: 'Rameshwaram' },
    { 'value': 1057, title: 'Ramnagar' },
    { 'value': 1792, title: 'Ramnagar' },
    { 'value': 1209, title: 'Ramnagaram' },
    { 'value': 1687, title: 'Rampur' },
    { 'value': 1688, title: 'Rampur Maniharan' },
    { 'value': 1847, title: 'Rampurhat' },
    { 'value': 1848, title: 'Ranaghat' },
    { 'value': 1181, title: 'Ranchi' },
    { 'value': 953, title: 'Rangia' },
    { 'value': 1516, title: 'Rasipuram' },
    { 'value': 1689, title: 'Rasra' },
    { 'value': 1690, title: 'Rath' },
    { 'value': 1279, title: 'Ratlam' },
    { 'value': 1328, title: 'Ratnagiri' },
    { 'value': 1386, title: 'Raurkela' },
    { 'value': 1058, title: 'Raxaul Bazar' },
    { 'value': 873, title: 'Rayachoti' },
    { 'value': 874, title: 'Rayadurg' },
    { 'value': 1387, title: 'Rayagada' },
    { 'value': 875, title: 'Renigunta' },
    { 'value': 1691, title: 'Renukoot' },
    { 'value': 1692, title: 'Reoti' },
    { 'value': 876, title: 'Repalle' },
    { 'value': 1059, title: 'Revelganj' },
    { 'value': 1280, title: 'Rewa' },
    { 'value': 1128, title: 'Rewari' },
    { 'value': 1793, title: 'Rishikesh' },
    { 'value': 1693, title: 'Robertsganj' },
    { 'value': 1129, title: 'Rohtak' },
    { 'value': 985, title: 'Rohtas' },
    { 'value': 1794, title: 'Roorkee' },
    { 'value': 1060, title: 'Rosera' },
    { 'value': 1694, title: 'Rudauli' },
    { 'value': 1695, title: 'Rudrapur' },
    { 'value': 1795, title: 'Rudrapur' },
    { 'value': 1407, title: 'Rupnagar' },
    { 'value': 1109, title: 'Sabar Kantha' },
    { 'value': 1696, title: 'Sadabad' },
    { 'value': 877, title: 'Sadasivpet' },
    { 'value': 1697, title: 'Safipur' },
    { 'value': 1281, title: 'Sagar' },
    { 'value': 1698, title: 'Saharanpur' },
    { 'value': 986, title: 'Saharsa' },
    { 'value': 1699, title: 'Sahaspur' },
    { 'value': 1700, title: 'Sahaswan' },
    { 'value': 1701, title: 'Sahawar' },
    { 'value': 1182, title: 'Sahibganj' },
    { 'value': 1702, title: 'Sahjanwa' },
    { 'value': 1703, title: 'Saidpur' },
    { 'value': 1849, title: 'Sainthia' },
    { 'value': 1517, title: 'Salem' },
    { 'value': 878, title: 'Salur' },
    { 'value': 879, title: 'Samalkot' },
    { 'value': 987, title: 'Samastipur' },
    { 'value': 1388, title: 'Sambalpur' },
    { 'value': 1704, title: 'Sambhal' },
    { 'value': 1705, title: 'Samdhan' },
    { 'value': 1706, title: 'Samthar' },
    { 'value': 1707, title: 'Sandi' },
    { 'value': 1708, title: 'Sandila' },
    { 'value': 880, title: 'Sangareddy' },
    { 'value': 1329, title: 'Sangli' },
    { 'value': 1408, title: 'Sangrur' },
    { 'value': 1518, title: 'Sankarankoil' },
    { 'value': 1519, title: 'Sankari' },
    { 'value': 1768, title: 'Sant Kabir Nagar' },
    { 'value': 1769, title: 'Sant Ravidas Nagar Bhadohi' },
    { 'value': 1850, title: 'Santipur' },
    { 'value': 1183, title: 'Saraikela' },
    { 'value': 988, title: 'Saran' },
    { 'value': 1709, title: 'Sardhana' },
    { 'value': 1410, title: 'SAS Nagar' },
    { 'value': 1061, title: 'Sasaram' },
    { 'value': 1330, title: 'Satara' },
    { 'value': 1520, title: 'Sathyamangalam' },
    { 'value': 1282, title: 'Satna' },
    { 'value': 881, title: 'Sattenapalle' },
    { 'value': 1521, title: 'Sattur' },
    { 'value': 1444, title: 'Sawai Madhopur' },
    { 'value': 916, title: 'Secunderabad' },
    { 'value': 1283, title: 'Sehore' },
    { 'value': 1710, title: 'Seohara' },
    { 'value': 1284, title: 'Seoni' },
    { 'value': 1711, title: 'Shahabad, Hardoi' },
    { 'value': 1712, title: 'Shahabad, Rampur' },
    { 'value': 1285, title: 'Shahdol' },
    { 'value': 1713, title: 'Shahganj' },
    { 'value': 1714, title: 'Shahjahanpur' },
    { 'value': 1286, title: 'Shajapur' },
    { 'value': 1715, title: 'Shamli' },
    { 'value': 1716, title: 'Shamsabad, Agra' },
    { 'value': 1717, title: 'Shamsabad, Farrukhabad' },
    { 'value': 989, title: 'Sheikhpura' },
    { 'value': 1522, title: 'Shenkottai' },
    { 'value': 990, title: 'Sheohar' },
    { 'value': 1287, title: 'Sheopur' },
    { 'value': 1062, title: 'Sherghati' },
    { 'value': 1718, title: 'Sherkot' },
    { 'value': 1719, title: 'Shikarpur, Bulandshahr' },
    { 'value': 1720, title: 'Shikohabad' },
    { 'value': 1349, title: 'Shillong' },
    { 'value': 1143, title: 'Shimla' },
    { 'value': 1210, title: 'Shimoga' },
    { 'value': 1721, title: 'Shishgarh' },
    { 'value': 1288, title: 'Shivpuri' },
    { 'value': 1523, title: 'Sholavandan' },
    { 'value': 1524, title: 'Sholingur' },
    { 'value': 1770, title: 'Shrawasti' },
    { 'value': 1722, title: 'Siana' },
    { 'value': 954, title: 'Sibsagar' },
    { 'value': 1771, title: 'Siddharthnagar' },
    { 'value': 882, title: 'Siddipet' },
    { 'value': 1289, title: 'Sidhi' },
    { 'value': 1723, title: 'Sikanderpur' },
    { 'value': 1724, title: 'Sikandra Rao' },
    { 'value': 1725, title: 'Sikandrabad' },
    { 'value': 1445, title: 'Sikar' },
    { 'value': 1063, title: 'Silao' },
    { 'value': 955, title: 'Silapathar' },
    { 'value': 956, title: 'Silchar' },
    { 'value': 1851, title: 'Siliguri' },
    { 'value': 1080, title: 'Silvassa' },
    { 'value': 1184, title: 'Simdega' },
    { 'value': 1331, title: 'Sindhudurg' },
    { 'value': 883, title: 'Singapur' },
    { 'value': 884, title: 'Sircilla' },
    { 'value': 1525, title: 'Sirkali' },
    { 'value': 1144, title: 'Sirmaur' },
    { 'value': 1446, title: 'Sirohi' },
    { 'value': 1130, title: 'Sirsa' },
    { 'value': 1726, title: 'Sirsaganj' },
    { 'value': 1727, title: 'Sirsi' },
    { 'value': 991, title: 'Sitamarhi' },
    { 'value': 1728, title: 'Sitapur' },
    { 'value': 1796, title: 'Sitarganj' },
    { 'value': 1526, title: 'Sivaganga' },
    { 'value': 1527, title: 'Sivagiri' },
    { 'value': 1528, title: 'Sivakasi' },
    { 'value': 992, title: 'Siwan' },
    { 'value': 1145, title: 'Solan' },
    { 'value': 1332, title: 'Solapur' },
    { 'value': 1852, title: 'Sonamukhi' },
    { 'value': 959, title: 'Sonapur' },
    { 'value': 1389, title: 'Sonapur' },
    { 'value': 1772, title: 'Sonbhadra' },
    { 'value': 1064, title: 'Sonepur' },
    { 'value': 1131, title: 'Sonipat' },
    { 'value': 1729, title: 'Soron' },
    { 'value': 885, title: 'Srikakulam' },
    { 'value': 886, title: 'Srikalahasti' },
    { 'value': 1159, title: 'Srinagar' },
    { 'value': 1853, title: 'Srirampore' },
    { 'value': 887, title: 'Srisailam Project (Right Flank Colony) Township' },
    { 'value': 1529, title: 'Srivilliputhur' },
    { 'value': 1730, title: 'Suar' },
    { 'value': 1065, title: 'Sugauli' },
    { 'value': 1066, title: 'Sultanganj' },
    { 'value': 1731, title: 'Sultanpur' },
    { 'value': 1732, title: 'Sumerpur' },
    { 'value': 1390, title: 'Sundargarh' },
    { 'value': 993, title: 'Supaul' },
    { 'value': 1530, title: 'Surandai' },
    { 'value': 1110, title: 'Surat' },
    { 'value': 1111, title: 'Surendranagar' },
    { 'value': 1854, title: 'Suri' },
    { 'value': 1531, title: 'Suriyampalayam' },
    { 'value': 888, title: 'Suryapet' },
    { 'value': 889, title: 'Tadepalligudem' },
    { 'value': 890, title: 'Tadpatri' },
    { 'value': 1855, title: 'Taki' },
    { 'value': 1346, title: 'Tamenglong' },
    { 'value': 1856, title: 'Tamluk' },
    { 'value': 1733, title: 'Tanda' },
    { 'value': 891, title: 'Tandur' },
    { 'value': 892, title: 'Tanuku' },
    { 'value': 1857, title: 'Tarakeswar' },
    { 'value': 1185, title: 'Tatanagar' },
    { 'value': 1340, title: 'Tatanagar' },
    { 'value': 920, title: 'Tawang' },
    { 'value': 1797, title: 'Tehri' },
    { 'value': 893, title: 'Tenali' },
    { 'value': 1532, title: 'Tenkasi' },
    { 'value': 1734, title: 'Tetri Bazar' },
    { 'value': 957, title: 'Tezpur' },
    { 'value': 1735, title: 'Thakurdwara' },
    { 'value': 1233, title: 'Thalassery' },
    { 'value': 1533, title: 'Thammampatti' },
    { 'value': 1736, title: 'Thana Bhawan' },
    { 'value': 1333, title: 'Thane' },
    { 'value': 1534, title: 'Thanjavur' },
    { 'value': 1535, title: 'Tharamangalam' },
    { 'value': 1536, title: 'Tharangambadi' },
    { 'value': 1587, title: 'Theni' },
    { 'value': 1537, title: 'Theni Allinagaram' },
    { 'value': 1538, title: 'Thirumangalam' },
    { 'value': 1539, title: 'Thirunindravur' },
    { 'value': 1540, title: 'Thiruparappu' },
    { 'value': 1541, title: 'Thirupuvanam' },
    { 'value': 1542, title: 'Thiruthuraipoondi' },
    { 'value': 1543, title: 'Thiruvallur' },
    { 'value': 1234, title: 'Thiruvananthapuram' },
    { 'value': 1544, title: 'Thiruvarur' },
    { 'value': 1545, title: 'Thoothukudi' },
    { 'value': 1347, title: 'Thoubal' },
    { 'value': 1235, title: 'Thrissur' },
    { 'value': 1546, title: 'Thuraiyur' },
    { 'value': 1290, title: 'Tikamgarh' },
    { 'value': 1737, title: 'Tilhar' },
    { 'value': 1547, title: 'Tindivanam' },
    { 'value': 958, title: 'Tinsukia' },
    { 'value': 1548, title: 'Tiruchendur' },
    { 'value': 1549, title: 'Tiruchengode' },
    { 'value': 1243, title: 'Tiruchirapalli' },
    { 'value': 1550, title: 'Tiruchirappalli' },
    { 'value': 1551, title: 'Tirukalukundram' },
    { 'value': 1552, title: 'Tirukkoyilur' },
    { 'value': 1553, title: 'Tirunelveli' },
    { 'value': 1554, title: 'Tirupathur' },
    { 'value': 1555, title: 'Tirupathur' },
    { 'value': 894, title: 'Tirupati' },
    { 'value': 1556, title: 'Tiruppur' },
    { 'value': 1557, title: 'Tiruttani' },
    { 'value': 1558, title: 'Tiruvannamalai' },
    { 'value': 1559, title: 'Tiruvethipuram' },
    { 'value': 1588, title: 'Tiruvottiyur' },
    { 'value': 895, title: 'Tiruvuru' },
    { 'value': 1738, title: 'Tirwaganj' },
    { 'value': 1560, title: 'Tittakudi' },
    { 'value': 1447, title: 'Tonk' },
    { 'value': 1244, title: 'Trichur' },
    { 'value': 1245, title: 'Trivandrum' },
    { 'value': 1739, title: 'Tulsipur' },
    { 'value': 1211, title: 'Tumkur' },
    { 'value': 1740, title: 'Tundla' },
    { 'value': 896, title: 'Tuni' },
    { 'value': 1350, title: 'Tura' },
    { 'value': 1451, title: 'Tuticorin' },
    { 'value': 1589, title: 'Tuticorin' },
    { 'value': 1448, title: 'Udaipur' },
    { 'value': 1599, title: 'Udaipur' },
    { 'value': 1561, title: 'Udhagamandalam' },
    { 'value': 1160, title: 'Udhampur' },
    { 'value': 1562, title: 'Udumalaipettai' },
    { 'value': 1212, title: 'Udupi' },
    { 'value': 1291, title: 'Ujjain' },
    { 'value': 1348, title: 'Ukhrul' },
    { 'value': 1334, title: 'Ulhasnagar' },
    { 'value': 1292, title: 'Umaria' },
    { 'value': 1146, title: 'Una' },
    { 'value': 1563, title: 'Unnamalaikadai' },
    { 'value': 1741, title: 'Unnao' },
    { 'value': 897, title: 'Uravakonda' },
    { 'value': 1564, title: 'Usilampatti' },
    { 'value': 1565, title: 'Uthamapalayam' },
    { 'value': 1566, title: 'Uthiramerur' },
    { 'value': 1742, title: 'Utraula' },
    { 'value': 1218, title: 'Uttara Kannada' },
    { 'value': 1236, title: 'Vadakara' },
    { 'value': 1567, title: 'Vadakkuvalliyur' },
    { 'value': 1568, title: 'Vadalur' },
    { 'value': 1569, title: 'Vadipatti' },
    { 'value': 1112, title: 'Vadodara' },
    { 'value': 994, title: 'Vaishali' },
    { 'value': 1570, title: 'Valparai' },
    { 'value': 1113, title: 'Valsad' },
    { 'value': 1571, title: 'Vandavasi' },
    { 'value': 1572, title: 'Vaniyambadi' },
    { 'value': 1743, title: 'Varanasi' },
    { 'value': 1089, title: 'Vasco da gama' },
    { 'value': 1573, title: 'Vedaranyam' },
    { 'value': 1574, title: 'Vellakoil' },
    { 'value': 1575, title: 'Vellore' },
    { 'value': 898, title: 'Venkatagiri' },
    { 'value': 899, title: 'Vicarabad' },
    { 'value': 1293, title: 'Vidisha' },
    { 'value': 900, title: 'Vijayawada' },
    { 'value': 1798, title: 'Vijaypur' },
    { 'value': 1576, title: 'Vikramasingapuram' },
    { 'value': 1577, title: 'Viluppuram' },
    { 'value': 901, title: 'Vinukonda' },
    { 'value': 1578, title: 'Virudhachalam' },
    { 'value': 1579, title: 'Virudhunagar' },
    { 'value': 902, title: 'Visakhapatnam' },
    { 'value': 1580, title: 'Viswanatham' },
    { 'value': 903, title: 'Vizianagaram' },
    { 'value': 1744, title: 'Vrindavan' },
    { 'value': 904, title: 'Wanaparthy' },
    { 'value': 905, title: 'Warangal' },
    { 'value': 1335, title: 'Wardha' },
    { 'value': 1745, title: 'Warhapur' },
    { 'value': 1067, title: 'Warisaliganj' },
    { 'value': 1336, title: 'Washim' },
    { 'value': 1237, title: 'Wayanad' },
    { 'value': 1217, title: 'Yadgir' },
    { 'value': 1132, title: 'Yamunanagar' },
    { 'value': 1337, title: 'Yavatmal' },
    { 'value': 906, title: 'Yellandu' },
    { 'value': 907, title: 'Yemmiganur' },
    { 'value': 908, title: 'Yerraguntla' },
    { 'value': 909, title: 'Zahirabad' },
    { 'value': 1746, title: 'Zaidpur' },
    { 'value': 1747, title: 'Zamania' }
]