export const GovAndAdminList =
        [
          {label: "Airport"},
          {label: "Banking"},
          {label: "Bureau-of-Immigration"},
          {label: "Commercial-Tax-Sales-Tax-VAT"},
          {label: "Customs-Excise-and-Service-Tax"},
          {label: "Education"},
          {label: "Electricity-and-Power-Supply"},
          {label: "Food-and-Drug-Administration"},
          {label: "Food-Civil-Supplies-and-Consumer-Affairs"},
          {label: "Foreign-Trade"},
          {label: "Forest"},
          {label: "Health-and-Family-Welfare" },
          {label: "Income-Tax"},
          {label: "Insurance"},
          {label: "Judiciary"},
          {label: "Labour"},
          {label: "Municipal-Services"},
          {label: "Others"},
          {label: "Passport"},
          {label: "Pension"},
          {label: "Police"},
          {label: "Post-Office"},
          {label: "Public-Sector-Undertakings"},
          {label: "Public-Services"},
          {label: "Public-Works-Department"},
          {label: "Railways"},
          {label: "Religious-Trusts"},
          {label: "Revenue"},
          {label: "Slum-Development"},
          {label: "Social-Welfare"},
          {label: "Stamps-and-Registration"},
          {label: "Telecom-Services"},
          {label: "Transport"},
          {label: "Urban-Development-Authorities"},
          {label: "Water-and-Sewage"}
    ]

